export const siteConfig = {
  name: "CalcMedical",
  shortName: "CalcMedical",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://calcmedical.com",
  description:
    "Free medical and surgical calculators for clinicians: eGFR CKD-EPI, EDD, EGA, GCS, Apgar, Parkland burns, CHA2DS2-VASc, MELD, pediatric weight, and 50+ more. Fast, self-contained, no account required.",
  locale: "en_US",
  twitter: "@calcmedical",
  adsenseClient: process.env.NEXT_PUBLIC_ADSENSE_CLIENT ?? "",
  keywords: [
    "medical calculator",
    "clinical calculator",
    "surgical calculator",
    "egfr calculator",
    "ckd-epi",
    "gcs score",
    "apgar score",
    "parkland formula",
    "edd calculator",
    "ega calculator",
    "gestational age calculator",
    "pediatric weight estimation",
    "cha2ds2-vasc",
    "has-bled",
    "meld-na",
    "wells score",
    "heart score",
    "bmi calculator medical",
    "body surface area",
    "anion gap calculator",
  ],
} as const;
