export const siteConfig = {
  name: "Calcmedical",
  shortName: "Calcmedical",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://calcmedical.fun",
  description:
    "Free medical and surgical calculators for doctors and nurses: eGFR CKD-EPI, EDD, EGA, GCS, Apgar, Parkland burns, CHA2DS2-VASc, MELD, pediatric weight, and 50+ more. Fast, self-contained, no account required.",
  locale: "en_US",
  twitter: "@calcmedical",
  adsenseClient: "ca-pub-8747052850575622",
  /** Keep false until AdSense approves the site — empty ad slots hurt review. */
  adsenseEnabled: false,
  contactEmail: "hadesanoye01@gmail.com",
  operatorName: "Calcmedical",
  keywords: [
    "medical calculators",
    "medical calculator",
    "surgical calculators",
    "surgical calculator",
    "egfr calculator",
    "ckd-epi",
    "gcs score",
    "apgar score",
    "parkland formula",
    "edd calculator",
    "ega calculator",
    "gestational age calculator",
    "pediatric weight estimation",
    "cha2ds2-vasc",
    "has-bled",
    "meld-na",
    "wells score",
    "heart score",
    "bmi calculator medical",
    "body surface area",
    "anion gap calculator",
  ],
} as const;
